ALTER TABLE subtitles
ADD COLUMN title VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN season INTEGER NOT NULL DEFAULT 0,
ADD COLUMN episode INTEGER NOT NULL DEFAULT 0,
ADD COLUMN media VARCHAR(50) NOT NULL DEFAULT '',
ADD COLUMN file_type VARCHAR(50) NOT NULL DEFAULT '',
ADD COLUMN deck_id INTEGER NOT NULL;
